---
- name: Build, Push and Run Docker Image for Python App
  hosts: localhost
  become: no
  gather_facts: no

  vars:
    image_name: "rodinu23/telerik"
    image_tag: "ansible-python-app-1.0"
    build_context: "/tmp/app"

  vars_files:
    - secrets.yaml

  tasks:
    - name: Create {{ build_context }} directory
      file:
        name: "{{ build_context }}"
        state: directory
        mode: 0755

    - name: Checkout repository
      git:
        repo: git@github.com:U23Rodin/Telerik
        dest: "{{ build_context}}"
        version: main
        update: yes

    - name: Build Docker image
      community.general.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ build_context }}"
        source: build

    - name: Log in to DockerHub
      community.general.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker Image
      community.general.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Run the container from the image
      community.general.docker_container:
        name: "python_app"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        auto_remove: yes
        published_ports:
          - "8080:80"
        env:
          PORT: "80"
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:80"]
          interval: 10s
          retries: 3
          start_period: 5s
