---
name: CI Pipeline

on:
  push:
    branches:
      - development

jobs:
  editorconfig-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check .editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker -verbose

  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Black
        run: pip install black
      - name: Check code format with Black
        run: black --check .

  pylint-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pylint
      - name: Analyse with Pylint
        run: pylint --disable=missing-docstring $(git ls-files '*.py')

  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '**/*.md'
          ignore: node_modules
          version: 0.28.1

  code-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run unittests
        run: python3 -m unittest app/app_test.py
