---
name: Homework Workflow

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'ansible/*'

jobs:
  pylint-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pylint
      - name: Analyse with Pylint
        run: pylint --disable=missing-docstring $(git ls-files '*.py')
